export const cssProperties = {
  // "transform: translateX(0px)": "translate-x-0",
  // "transform: translateY(0px)": "translate-y-0",
  // "transform: translateX(1px)": "translate-x-px",
  // "transform: translateY(1px)": "translate-y-px",
  // "transform: translateX(0.125rem)": "translate-x-0.5",
  // "transform: translateY(0.125rem)": "translate-y-0.5",
  // "transform: translateX(0.25rem)": "translate-x-1",
  // "transform: translateY(0.25rem)": "translate-y-1",
  // "transform: translateX(0.375rem)": "translate-x-1.5",
  // "transform: translateY(0.375rem)": "translate-y-1.5",
  // "transform: translateX(0.5rem)": "translate-x-2",
  // "transform: translateY(0.5rem)": "translate-y-2",
  // "transform: translateX(0.625rem)": "translate-x-2.5",
  // "transform: translateY(0.625rem)": "translate-y-2.5",
  // "transform: translateX(0.75rem)": "translate-x-3",
  // "transform: translateY(0.75rem)": "translate-y-3",
  // "transform: translateX(0.875rem)": "translate-x-3.5",
  // "transform: translateY(0.875rem)": "translate-y-3.5",
  // "transform: translateX(1rem)": "translate-x-4",
  // "transform: translateY(1rem)": "translate-y-4",
  // "transform: translateX(1.25rem)": "translate-x-5",
  // "transform: translateY(1.25rem)": "translate-y-5",
  // "transform: translateX(1.5rem)": "translate-x-6",
  // "transform: translateY(1.5rem)": "translate-y-6",
  // "transform: translateX(1.75rem)": "translate-x-7",
  // "transform: translateY(1.75rem)": "translate-y-7",
  // "transform: translateX(2rem)": "translate-x-8",
  // "transform: translateY(2rem)": "translate-y-8",
  // "transform: translateX(2.25rem)": "translate-x-9",
  // "transform: translateY(2.25rem)": "translate-y-9",
  // "transform: translateX(2.5rem)": "translate-x-10",
  // "transform: translateY(2.5rem)": "translate-y-10",
  // "transform: translateX(2.75rem)": "translate-x-11",
  // "transform: translateY(2.75rem)": "translate-y-11",
  // "transform: translateX(3rem)": "translate-x-12",
  // "transform: translateY(3rem)": "translate-y-12",
  // "transform: translateX(3.5rem)": "translate-x-14",
  // "transform: translateY(3.5rem)": "translate-y-14",
  // "transform: translateX(4rem)": "translate-x-16",
  // "transform: translateY(4rem)": "translate-y-16",
  // "transform: translateX(5rem)": "translate-x-20",
  // "transform: translateY(5rem)": "translate-y-20",
  // "transform: translateX(6rem)": "translate-x-24",
  // "transform: translateY(6rem)": "translate-y-24",
  // "transform: translateX(7rem)": "translate-x-28",
  // "transform: translateY(7rem)": "translate-y-28",
  // "transform: translateX(8rem)": "translate-x-32",
  // "transform: translateY(8rem)": "translate-y-32",
  // "transform: translateX(9rem)": "translate-x-36",
  // "transform: translateY(9rem)": "translate-y-36",
  // "transform: translateX(10rem)": "translate-x-40",
  // "transform: translateY(10rem)": "translate-y-40",
  // "transform: translateX(11rem)": "translate-x-44",
  // "transform: translateY(11rem)": "translate-y-44",
  // "transform: translateX(12rem)": "translate-x-48",
  // "transform: translateY(12rem)": "translate-y-48",
  // "transform: translateX(13rem)": "translate-x-52",
  // "transform: translateY(13rem)": "translate-y-52",
  // "transform: translateX(14rem)": "translate-x-56",
  // "transform: translateY(14rem)": "translate-y-56",
  // "transform: translateX(15rem)": "translate-x-60",
  // "transform: translateY(15rem)": "translate-y-60",
  // "transform: translateX(16rem)": "translate-x-64",
  // "transform: translateY(16rem)": "translate-y-64",
  // "transform: translateX(18rem)": "translate-x-72",
  // "transform: translateY(18rem)": "translate-y-72",
  // "transform: translateX(20rem)": "translate-x-80",
  // "transform: translateY(20rem)": "translate-y-80",
  // "transform: translateX(24rem)": "translate-x-96",
  // "transform: translateY(24rem)": "translate-y-96",
  // "transform: translateX(100%)": "translate-x-full",
  // "transform: translateY(100%)": "translate-y-full",
  "align-items: baseline": "items-baseline",
  "align-items: center": "items-center",
  "align-items: flex-end": "items-end",
  "align-items: flex-start": "items-start",
  "align-items: stretch": "items-stretch",
  "align-self: auto": "self-auto",
  "align-self: baseline": "self-baseline",
  "align-self: center": "self-center",
  "align-self: flex-end": "self-end",
  "align-self: flex-start": "self-start",
  "align-self: stretch": "self-stretch",
  "display: block": "block",
  "display: contents": "contents",
  "display: flex": "flex",
  "display: flow-root": "flow-root",
  "display: grid": "grid",
  "display: inline-block": "inline-block",
  "display: inline-flex": "inline-flex",
  "display: inline-grid": "inline-grid",
  "display: inline-table": "inline-table",
  "display: inline": "inline",
  "display: list-item": "list-item",
  "display: none": "hidden",
  "display: table-caption": "table-caption",
  "display: table-cell": "table-cell",
  "display: table-column-group": "table-column-group",
  "display: table-column": "table-column",
  "display: table-footer-group": "table-footer-group",
  "display: table-header-group": "table-header-group",
  "display: table-row-group": "table-row-group",
  "display: table-row": "table-row",
  "display: table": "table",
  "flex-direction: column-reverse": "flex-col-reverse",
  "flex-direction: column": "flex-col",
  "flex-direction: column": "flex-col",
  "flex-direction: row-reverse": "flex-row-reverse",
  "flex-direction: row": "flex-row",
  "flex: 0 1 auto": "flex-initial",
  "flex: 1 1 0%": "flex-1",
  "flex: 1 1 auto": "flex-auto",
  "flex: none": "flex-none",
  "gap-0.5": "gap: 2px",
  "gap-0": "gap: 0px",
  "gap-1.5": "gap: 6px",
  "gap-1": "gap: 4px",
  "gap-10": "gap: 40px",
  "gap-11": "gap: 44px",
  "gap-12": "gap: 48px",
  "gap-14": "gap: 56px",
  "gap-2.5": "gap: 10px",
  "gap-2": "gap: 8px",
  "gap-20": "gap: 80px",
  "gap-3.5": "gap: 14px",
  "gap-3": "gap: 12px",
  "gap-4": "gap: 16px",
  "gap-40": "gap: 160px",
  "gap-5": "gap: 20px",
  "gap-6": "gap: 24px",
  "gap-7": "gap: 28px",
  "gap-8": "gap: 32px",
  "gap-80": "gap: 320px",
  "gap-9": "gap: 36px",
  "gap-px": "gap: 1px",
  "gap-x-0.5": "column-gap: 2px",
  "gap-x-0": "column-gap: 0px",
  "gap-x-1.5": "column-gap: 6px",
  "gap-x-1": "column-gap: 4px",
  "gap-x-10": "column-gap: 40px",
  "gap-x-11": "column-gap: 44px",
  "gap-x-12": "column-gap: 48px",
  "gap-x-14": "column-gap: 56px",
  "gap-x-2.5": "column-gap: 10px",
  "gap-x-2": "column-gap: 8px",
  "gap-x-20": "column-gap: 80px",
  "gap-x-3.5": "column-gap: 14px",
  "gap-x-3": "column-gap: 12px",
  "gap-x-4": "column-gap: 16px",
  "gap-x-40": "column-gap: 160px",
  "gap-x-5": "column-gap: 20px",
  "gap-x-6": "column-gap: 24px",
  "gap-x-7": "column-gap: 28px",
  "gap-x-8": "column-gap: 32px",
  "gap-x-80": "column-gap: 320px",
  "gap-x-9": "column-gap: 36px",
  "gap-x-px": "column-gap: 1px",
  "gap-y-0.5": "row-gap: 2px",
  "gap-y-0": "row-gap: 0px",
  "gap-y-1.5": "row-gap: 6px",
  "gap-y-1": "row-gap: 4px",
  "gap-y-10": "row-gap: 40px",
  "gap-y-11": "row-gap: 44px",
  "gap-y-12": "row-gap: 48px",
  "gap-y-14": "row-gap: 56px",
  "gap-y-2.5": "row-gap: 10px",
  "gap-y-2": "row-gap: 8px",
  "gap-y-20": "row-gap: 80px",
  "gap-y-3.5": "row-gap: 14px",
  "gap-y-3": "row-gap: 12px",
  "gap-y-4": "row-gap: 16px",
  "gap-y-40": "row-gap: 160px",
  "gap-y-5": "row-gap: 20px",
  "gap-y-6": "row-gap: 24px",
  "gap-y-7": "row-gap: 28px",
  "gap-y-8": "row-gap: 32px",
  "gap-y-80": "row-gap: 320px",
  "gap-y-9": "row-gap: 36px",
  "gap-y-px": "row-gap: 1px",
  "height: 0px": "h-0",
  "height: 100%": "h-full",
  "height: 100vh": "h-screen",
  "height: 10px": "h-2.5",
  "height: 12px": "h-3",
  "height: 14px": "h-3.5",
  "height: 160px": "h-40",
  "height: 16px": "h-4",
  "height: 1px": "h-px",
  "height: 20px": "h-5",
  "height: 24px": "h-6",
  "height: 28px": "h-7",
  "height: 2px": "h-0.5",
  "height: 320px": "h-80",
  "height: 32px": "h-8",
  "height: 36px": "h-9",
  "height: 40px": "h-10",
  "height: 44px": "h-11",
  "height: 48px": "h-12",
  "height: 4px": "h-1",
  "height: 56px": "h-14",
  "height: 6px": "h-1.5",
  "height: 80px": "h-20",
  "height: 8px": "h-2",
  "height: auto": "h-auto",
  "height: fit-content": "h-fit",
  "height: max-content": "h-max",
  "height: min-content": "h-min",
  "justify-content: center": "justify-center",
  "justify-content: flex-end": "justify-end",
  "justify-content: flex-start": "justify-start",
  "justify-content: normal": "justify-normal",
  "justify-content: space-around": "justify-around",
  "justify-content: space-between": "justify-between",
  "justify-content: space-evenly": "justify-evenly",
  "justify-content: stretch": "justify-stretch",
  "justify-self: auto": "justify-self-auto",
  "justify-self: center": "justify-self-center",
  "justify-self: end": "justify-self-end",
  "justify-self: start": "justify-self-start",
  "justify-self: stretch": "justify-self-stretch",
  "margin-block: 0px": "my-0",
  "margin-block: 10px": "my-2.5",
  "margin-block: 12px": "my-3",
  "margin-block: 14px": "my-3.5",
  "margin-block: 160px": "my-40",
  "margin-block: 16px": "my-4",
  "margin-block: 1px": "my-px",
  "margin-block: 20px": "my-5",
  "margin-block: 24px": "my-6",
  "margin-block: 28px": "my-7",
  "margin-block: 2px": "my-0.5",
  "margin-block: 320px": "my-80",
  "margin-block: 32px": "my-8",
  "margin-block: 36px": "my-9",
  "margin-block: 40px": "my-10",
  "margin-block: 48px": "my-12",
  "margin-block: 4px": "my-1",
  "margin-block: 6px": "my-1.5",
  "margin-block: 80px": "my-20",
  "margin-block: 8px": "my-2",
  "margin-bottom: 0px": "mb-0",
  "margin-bottom: 10px": "mb-2.5",
  "margin-bottom: 12px": "mb-3",
  "margin-bottom: 14px": "mb-3.5",
  "margin-bottom: 160px": "mb-40",
  "margin-bottom: 16px": "mb-4",
  "margin-bottom: 1px": "mb-px",
  "margin-bottom: 20px": "mb-5",
  "margin-bottom: 24px": "mb-6",
  "margin-bottom: 28px": "mb-7",
  "margin-bottom: 2px": "mb-0.5",
  "margin-bottom: 320px": "mb-80",
  "margin-bottom: 32px": "mb-8",
  "margin-bottom: 36px": "mb-9",
  "margin-bottom: 40px": "mb-10",
  "margin-bottom: 48px": "mb-12",
  "margin-bottom: 4px": "mb-1",
  "margin-bottom: 6px": "mb-1.5",
  "margin-bottom: 80px": "mb-20",
  "margin-bottom: 8px": "mb-2",
  "margin-inline: 0px": "mx-0",
  "margin-inline: 10px": "mx-2.5",
  "margin-inline: 12px": "mx-3",
  "margin-inline: 14px": "mx-3.5",
  "margin-inline: 160px": "mx-40",
  "margin-inline: 16px": "mx-4",
  "margin-inline: 1px": "mx-px",
  "margin-inline: 20px": "mx-5",
  "margin-inline: 24px": "mx-6",
  "margin-inline: 28px": "mx-7",
  "margin-inline: 2px": "mx-0.5",
  "margin-inline: 320px": "mx-80",
  "margin-inline: 32px": "mx-8",
  "margin-inline: 36px": "mx-9",
  "margin-inline: 40px": "mx-10",
  "margin-inline: 48px": "mx-12",
  "margin-inline: 4px": "mx-1",
  "margin-inline: 6px": "mx-1.5",
  "margin-inline: 80px": "mx-20",
  "margin-inline: 8px": "mx-2",
  "margin-left: 0px": "ml-0",
  "margin-left: 10px": "ml-2.5",
  "margin-left: 12px": "ml-3",
  "margin-left: 14px": "ml-3.5",
  "margin-left: 160px": "ml-40",
  "margin-left: 16px": "ml-4",
  "margin-left: 1px": "ml-px",
  "margin-left: 20px": "ml-5",
  "margin-left: 24px": "ml-6",
  "margin-left: 28px": "ml-7",
  "margin-left: 2px": "ml-0.5",
  "margin-left: 320px": "ml-80",
  "margin-left: 32px": "ml-8",
  "margin-left: 36px": "ml-9",
  "margin-left: 40px": "ml-10",
  "margin-left: 48px": "ml-12",
  "margin-left: 4px": "ml-1",
  "margin-left: 6px": "ml-1.5",
  "margin-left: 80px": "ml-20",
  "margin-left: 8px": "ml-2",
  "margin-right: 0px": "mr-0",
  "margin-right: 10px": "mr-2.5",
  "margin-right: 12px": "mr-3",
  "margin-right: 14px": "mr-3.5",
  "margin-right: 160px": "mr-40",
  "margin-right: 16px": "mr-4",
  "margin-right: 1px": "mr-px",
  "margin-right: 20px": "mr-5",
  "margin-right: 24px": "mr-6",
  "margin-right: 28px": "mr-7",
  "margin-right: 2px": "mr-0.5",
  "margin-right: 320px": "mr-80",
  "margin-right: 32px": "mr-8",
  "margin-right: 36px": "mr-9",
  "margin-right: 40px": "mr-10",
  "margin-right: 48px": "mr-12",
  "margin-right: 4px": "mr-1",
  "margin-right: 6px": "mr-1.5",
  "margin-right: 80px": "mr-20",
  "margin-right: 8px": "mr-2",
  "margin-top: 0px": "mt-0",
  "margin-top: 10px": "mt-2.5",
  "margin-top: 12px": "mt-3",
  "margin-top: 14px": "mt-3.5",
  "margin-top: 160px": "mt-40",
  "margin-top: 16px": "mt-4",
  "margin-top: 1px": "mt-px",
  "margin-top: 20px": "mt-5",
  "margin-top: 24px": "mt-6",
  "margin-top: 28px": "mt-7",
  "margin-top: 2px": "mt-0.5",
  "margin-top: 320px": "mt-80",
  "margin-top: 32px": "mt-8",
  "margin-top: 36px": "mt-9",
  "margin-top: 40px": "mt-10",
  "margin-top: 48px": "mt-12",
  "margin-top: 4px": "mt-1",
  "margin-top: 6px": "mt-1.5",
  "margin-top: 80px": "mt-20",
  "margin-top: 8px": "mt-2",
  "margin: 0px": "m-0",
  "margin: 10px": "m-2.5",
  "margin: 12px": "m-3",
  "margin: 14px": "m-3.5",
  "margin: 160px": "m-40",
  "margin: 16px": "m-4",
  "margin: 1px": "m-px",
  "margin: 20px": "m-5",
  "margin: 24px": "m-6",
  "margin: 28px": "m-7",
  "margin: 2px": "m-0.5",
  "margin: 320px": "m-80",
  "margin: 32px": "m-8",
  "margin: 36px": "m-9",
  "margin: 40px": "m-10",
  "margin: 48px": "m-12",
  "margin: 4px": "m-1",
  "margin: 6px": "m-1.5",
  "margin: 80px": "m-20",
  "margin: 8px": "m-2",
  "max-height: 0px": "max-h-0",
  "max-height: 100%": "max-h-full",
  "max-height: 100vh": "max-h-screen",
  "max-height: 10px": "max-h-2.5",
  "max-height: 12px": "max-h-3",
  "max-height: 14px": "max-h-3.5",
  "max-height: 160px": "max-h-40",
  "max-height: 16px": "max-h-4",
  "max-height: 1px": "max-h-px",
  "max-height: 20px": "max-h-5",
  "max-height: 24px": "max-h-6",
  "max-height: 28px": "max-h-7",
  "max-height: 2px": "max-h-0.5",
  "max-height: 320px": "max-h-80",
  "max-height: 32px": "max-h-8",
  "max-height: 36px": "max-h-9",
  "max-height: 40px": "max-h-10",
  "max-height: 44px": "max-h-11",
  "max-height: 48px": "max-h-12",
  "max-height: 4px": "max-h-1",
  "max-height: 56px": "max-h-14",
  "max-height: 6px": "max-h-1.5",
  "max-height: 80px": "max-h-20",
  "max-height: 8px": "max-h-2",
  "max-height: fit-content": "max-h-fit",
  "max-height: max-content": "max-h-max",
  "max-height: min-content": "max-h-min",
  "max-height: none": "max-h-none",
  "max-width: 0px": "max-w-0",
  "max-width: 100%": "max-w-full",
  "max-width: 1024px": "max-w-5xl",
  "max-width: 1024px": "max-w-screen-lg",
  "max-width: 1152px": "max-w-6xl",
  "max-width: 1280px": "max-w-7xl",
  "max-width: 1280px": "max-w-screen-xl",
  "max-width: 1536px": "max-w-screen-2xl",
  "max-width: 320px": "max-w-xs",
  "max-width: 448px": "max-w-md",
  "max-width: 512px": "max-w-lg",
  "max-width: 576px": "max-w-xl",
  "max-width: 640px": "max-w-screen-sm",
  "max-width: 65ch": "max-w-prose",
  "max-width: 672px": "max-w-2xl",
  "max-width: 768px": "max-w-3xl",
  "max-width: 768px": "max-w-screen-md",
  "max-width: fit-content": "max-w-fit",
  "max-width: max-content": "max-w-max",
  "max-width: min-content": "max-w-min",
  "max-width: none": "max-w-none",
  "min-height: 0px": "min-h-0",
  "min-height: 100%": "min-h-full",
  "min-height: 100vh": "min-h-screen",
  "min-height: fit-content": "min-h-fit",
  "min-height: max-content": "min-h-max",
  "min-height: min-content": "min-h-min",
  "min-width: 0px": "min-w-0",
  "min-width: 100%": "min-w-full",
  "min-width: max-content": "min-w-max",
  "min-width: min-content": "min-w-min",
  "padding-block: 0px": "py-0",
  "padding-block: 10px": "py-2.5",
  "padding-block: 12px": "py-3",
  "padding-block: 14px": "py-3.5",
  "padding-block: 160px": "py-40",
  "padding-block: 16px": "py-4",
  "padding-block: 1px": "py-px",
  "padding-block: 20px": "py-5",
  "padding-block: 24px": "py-6",
  "padding-block: 28px": "py-7",
  "padding-block: 2px": "py-0.5",
  "padding-block: 320px": "py-80",
  "padding-block: 32px": "py-8",
  "padding-block: 36px": "py-9",
  "padding-block: 40px": "py-10",
  "padding-block: 48px": "py-12",
  "padding-block: 4px": "py-1",
  "padding-block: 6px": "py-1.5",
  "padding-block: 80px": "py-20",
  "padding-block: 8px": "py-2",
  "padding-bottom: 0px": "pb-0",
  "padding-bottom: 10px": "pb-2.5",
  "padding-bottom: 12px": "pb-3",
  "padding-bottom: 14px": "pb-3.5",
  "padding-bottom: 160px": "pb-40",
  "padding-bottom: 16px": "pb-4",
  "padding-bottom: 1px": "pb-px",
  "padding-bottom: 20px": "pb-5",
  "padding-bottom: 24px": "pb-6",
  "padding-bottom: 28px": "pb-7",
  "padding-bottom: 2px": "pb-0.5",
  "padding-bottom: 320px": "pb-80",
  "padding-bottom: 32px": "pb-8",
  "padding-bottom: 36px": "pb-9",
  "padding-bottom: 40px": "pb-10",
  "padding-bottom: 48px": "pb-12",
  "padding-bottom: 4px": "pb-1",
  "padding-bottom: 6px": "pb-1.5",
  "padding-bottom: 80px": "pb-20",
  "padding-bottom: 8px": "pb-2",
  "padding-inline: 0px": "px-0",
  "padding-inline: 10px": "px-2.5",
  "padding-inline: 12px": "px-3",
  "padding-inline: 14px": "px-3.5",
  "padding-inline: 160px": "px-40",
  "padding-inline: 16px": "px-4",
  "padding-inline: 1px": "px-px",
  "padding-inline: 20px": "px-5",
  "padding-inline: 24px": "px-6",
  "padding-inline: 28px": "px-7",
  "padding-inline: 2px": "px-0.5",
  "padding-inline: 320px": "px-80",
  "padding-inline: 32px": "px-8",
  "padding-inline: 36px": "px-9",
  "padding-inline: 40px": "px-10",
  "padding-inline: 48px": "px-12",
  "padding-inline: 4px": "px-1",
  "padding-inline: 6px": "px-1.5",
  "padding-inline: 80px": "px-20",
  "padding-inline: 8px": "px-2",
  "padding-left: 0px": "pl-0",
  "padding-left: 10px": "pl-2.5",
  "padding-left: 12px": "pl-3",
  "padding-left: 14px": "pl-3.5",
  "padding-left: 160px": "pl-40",
  "padding-left: 16px": "pl-4",
  "padding-left: 1px": "pl-px",
  "padding-left: 20px": "pl-5",
  "padding-left: 24px": "pl-6",
  "padding-left: 28px": "pl-7",
  "padding-left: 2px": "pl-0.5",
  "padding-left: 320px": "pl-80",
  "padding-left: 32px": "pl-8",
  "padding-left: 36px": "pl-9",
  "padding-left: 40px": "pl-10",
  "padding-left: 48px": "pl-12",
  "padding-left: 4px": "pl-1",
  "padding-left: 6px": "pl-1.5",
  "padding-left: 80px": "pl-20",
  "padding-left: 8px": "pl-2",
  "padding-right: 0px": "pr-0",
  "padding-right: 10px": "pr-2.5",
  "padding-right: 12px": "pr-3",
  "padding-right: 14px": "pr-3.5",
  "padding-right: 160px": "pr-40",
  "padding-right: 16px": "pr-4",
  "padding-right: 1px": "pr-px",
  "padding-right: 20px": "pr-5",
  "padding-right: 24px": "pr-6",
  "padding-right: 28px": "pr-7",
  "padding-right: 2px": "pr-0.5",
  "padding-right: 320px": "pr-80",
  "padding-right: 32px": "pr-8",
  "padding-right: 36px": "pr-9",
  "padding-right: 40px": "pr-10",
  "padding-right: 48px": "pr-12",
  "padding-right: 4px": "pr-1",
  "padding-right: 6px": "pr-1.5",
  "padding-right: 80px": "pr-20",
  "padding-right: 8px": "pr-2",
  "padding-top: 0px": "pt-0",
  "padding-top: 10px": "pt-2.5",
  "padding-top: 12px": "pt-3",
  "padding-top: 14px": "pt-3.5",
  "padding-top: 160px": "pt-40",
  "padding-top: 16px": "pt-4",
  "padding-top: 1px": "pt-px",
  "padding-top: 20px": "pt-5",
  "padding-top: 24px": "pt-6",
  "padding-top: 28px": "pt-7",
  "padding-top: 2px": "pt-0.5",
  "padding-top: 320px": "pt-80",
  "padding-top: 32px": "pt-8",
  "padding-top: 36px": "pt-9",
  "padding-top: 40px": "pt-10",
  "padding-top: 48px": "pt-12",
  "padding-top: 4px": "pt-1",
  "padding-top: 6px": "pt-1.5",
  "padding-top: 80px": "pt-20",
  "padding-top: 8px": "pt-2",
  "padding: 0px": "p-0",
  "padding: 10px": "p-2.5",
  "padding: 12px": "p-3",
  "padding: 14px": "p-3.5",
  "padding: 160px": "p-40",
  "padding: 16px": "p-4",
  "padding: 1px": "p-px",
  "padding: 20px": "p-5",
  "padding: 24px": "p-6",
  "padding: 28px": "p-7",
  "padding: 2px": "p-0.5",
  "padding: 320px": "p-80",
  "padding: 32px": "p-8",
  "padding: 36px": "p-9",
  "padding: 40px": "p-10",
  "padding: 48px": "p-12",
  "padding: 4px": "p-1",
  "padding: 6px": "p-1.5",
  "padding: 80px": "p-20",
  "padding: 8px": "p-2",
  "position: absolute": "absolute",
  "position: fixed": "fixed",
  "position: relative": "relative",
  "position: static": "static",
  "position: sticky": "sticky",
  "resize: both": "resize",
  "resize: horizontal": "resize-x",
  "resize: none": "resize-none",
  "resize: vertical": "resize-y",
  "transform-origin: bottom left": "origin-bottom-left",
  "transform-origin: bottom right": "origin-bottom-right",
  "transform-origin: bottom": "origin-bottom",
  "transform-origin: center": "origin-center",
  "transform-origin: left": "origin-left",
  "transform-origin: right": "origin-right",
  "transform-origin: top left": "origin-top-left",
  "transform-origin: top right": "origin-top-right",
  "transform-origin: top": "origin-top",
  "transform: rotate(0deg)": "rotate-0",
  "transform: rotate(12deg)": "rotate-12",
  "transform: rotate(180deg)": "rotate-180",
  "transform: rotate(1deg)": "rotate-1",
  "transform: rotate(2deg)": "rotate-2",
  "transform: rotate(3deg)": "rotate-3",
  "transform: rotate(45deg)": "rotate-45",
  "transform: rotate(6deg)": "rotate-6",
  "transform: rotate(90deg)": "rotate-90",
  "transform: scale(.5)": "scale-50",
  "transform: scale(.75)": "scale-75",
  "transform: scale(.9)": "scale-90",
  "transform: scale(.95)": "scale-95",
  "transform: scale(0)": "scale-0",
  "transform: scale(1.05)": "scale-105",
  "transform: scale(1.1)": "scale-110",
  "transform: scale(1.25)": "scale-125",
  "transform: scale(1.5)": "scale-150",
  "transform: scale(1)": "scale-100",
  "transform: scaleX(.5)": "scale-x-50",
  "transform: scaleX(.75)": "scale-x-75",
  "transform: scaleX(.9)": "scale-x-90",
  "transform: scaleX(.95)": "scale-x-95",
  "transform: scaleX(0)": "scale-x-0",
  "transform: scaleX(1.05)": "scale-x-105",
  "transform: scaleX(1.1)": "scale-x-110",
  "transform: scaleX(1.25)": "scale-x-125",
  "transform: scaleX(1.5)": "scale-x-150",
  "transform: scaleX(1)": "scale-x-100",
  "transform: scaleY(.5)": "scale-y-50",
  "transform: scaleY(.75)": "scale-y-75",
  "transform: scaleY(.9)": "scale-y-90",
  "transform: scaleY(.95)": "scale-y-95",
  "transform: scaleY(0)": "scale-y-0",
  "transform: scaleY(1.05)": "scale-y-105",
  "transform: scaleY(1.1)": "scale-y-110",
  "transform: scaleY(1.25)": "scale-y-125",
  "transform: scaleY(1.5)": "scale-y-150",
  "transform: scaleY(1)": "scale-y-100",
  "transform: skewX(0deg)": "skew-x-0",
  "transform: skewX(12deg)": "skew-x-12",
  "transform: skewX(1deg)": "skew-x-1",
  "transform: skewX(2deg)": "skew-x-2",
  "transform: skewX(3deg)": "skew-x-3",
  "transform: skewX(6deg)": "skew-x-6",
  "transform: skewY(0deg)": "skew-y-0",
  "transform: skewY(12deg)": "skew-y-12",
  "transform: skewY(1deg)": "skew-y-1",
  "transform: skewY(2deg)": "skew-y-2",
  "transform: skewY(3deg)": "skew-y-3",
  "transform: skewY(6deg)": "skew-y-6",
  "transition-duration: 0s": "duration-0",
  "transition-duration: 1000ms": "duration-1000",
  "transition-duration: 100ms": "duration-100",
  "transition-duration: 150ms": "duration-150",
  "transition-duration: 200ms": "duration-200",
  "transition-duration: 300ms": "duration-300",
  "transition-duration: 500ms": "duration-500",
  "transition-duration: 700ms": "duration-700",
  "transition-duration: 75ms": "duration-75",
  "user-select: all": "select-all",
  "user-select: auto": "select-auto",
  "user-select: none": "select-none",
  "user-select: text": "select-text",
  "width: 0px": "w-0",
  "width: 100%": "w-full",
  "width: 100vw": "w-screen",
  "width: 10px": "w-2.5",
  "width: 12px": "w-3",
  "width: 14px": "w-3.5",
  "width: 160px": "w-40",
  "width: 16px": "w-4",
  "width: 1px": "w-px",
  "width: 20px": "w-5",
  "width: 24px": "w-6",
  "width: 28px": "w-7",
  "width: 2px": "w-0.5",
  "width: 320px": "w-80",
  "width: 32px": "w-8",
  "width: 36px": "w-9",
  "width: 40px": "w-10",
  "width: 44px": "w-11",
  "width: 48px": "w-12",
  "width: 4px": "w-1",
  "width: 56px": "w-14",
  "width: 6px": "w-1.5",
  "width: 80px": "w-20",
  "width: 8px": "w-2",
  "width: auto": "w-auto",
  "width: fit-content": "w-fit",
  "width: max-content": "w-max",
  "width: min-content": "w-min",
  "z-index: 0": "z-0",
  "z-index: 10": "z-10",
  "z-index: 20": "z-20",
  "z-index: 30": "z-30",
  "z-index: 40": "z-40",
  "z-index: 50": "z-50",
  "z-index: auto": "z-auto",
};
